apiVersion: v1
kind: Secret
metadata:
  name: bitnamicharts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: registry-1.docker.io/bitnamicharts
  name: bitnamicharts
  type: helm
  enableOCI: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    chart: prometheus
    helm:
      values: |
        server:
          service:
            type: "ClusterIP"
          ingress:
            enabled: true
            hostname: "prometheus.rd.localhost"
            tls: true
            selfSigned: true
        alertmanager:
          enabled: false
        pushgateway:
          enabled: false
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 0.1.8
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:    
    - CreateNamespace=true 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    chart: grafana
    helm:
      values: |
        service:
          type: "ClusterIP"
        ingress:
          enabled: true
          hostname: "grafana.rd.localhost"
          tls: true
          selfSigned: true
        admin:
          password: "password"
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 9.0.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:    
    - CreateNamespace=true 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |
        service:
          type: "ClusterIP"
        ingress:
          enabled: true
          hostname: "grafana.rd.localhost"
          tls: true
          selfSigned: true
        admin:
          password: "password"
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 48.3.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:    
    - CreateNamespace=true 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    chart: rancher-monitoring
    helm:
      values: |
        service:
          type: "ClusterIP"
        ingress:
          enabled: true
          hostname: "grafana.rd.localhost"
          tls: true
          selfSigned: true
        admin:
          password: "password"
    repoURL: https://github.com/rancher/charts
    targetRevision: 102.0.2+up40.1.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:    
    - CreateNamespace=true 